### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by mican-wan2** [mican-wan2/assessment#1]
以下の結果を追加したい。

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振る舞いに多くの人が癒されています。'

**Comment by kukuku-wanwan** [comment]
いいと思います。対応してください。

**Comment by mican-wan2** [comment]
9f76c0d で対応されました。

**Comment by mican-wan2** [comment]
9f76c0d で対応されました。
